name: Run Magnitude Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MAGNITUDE_API_KEY: ${{ secrets.MAGNITUDE_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
          
      - name: Install dependencies
        run: bun install
        
      - name: Start development server
        run: bun run dev &
        
      - name: Wait for server to start
        run: sleep 5
        
      - name: Run tests
        run: bun run magnitude